ratings:
  paths: 
  - "**/*.go"

exclude_paths:
- test/
- Godeps/
- thirdparty/
- "**/*.pb.go"

engines:
  fixme:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
